import type { Metadata } from "next";
import "./globals.scss";

export const metadata: Metadata = {
  title: "Codewithg.com | Guillaume Duhan aka Codewithguillaume",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`container`}
      >
        {children}
      </body>
    </html>
  );
}
