import DarkMode from '@/components/DarkMode';
import Menu from "@/components/Menu";
import type { Metadata } from "next";
import { ViewTransitions } from 'next-view-transitions';
import { Suspense } from 'react';
import "./globals.scss";

export const metadata: Metadata = {
  title: "Codewithg.com | Guillaume Duhan aka Codewithguillaume",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <ViewTransitions>
        <body
          className={`p-2 xl:p-6 grid gap-4`}
        >
          <header className="flex items-center justify-between">
            <Menu />
            <DarkMode />
          </header>
          <Suspense>
            {children}
          </Suspense>
        </body>
      </ViewTransitions>
    </html>
  );
}
