import DarkMode from "@/components/DarkMode";
import type { Metadata } from "next";
import { ViewTransitions } from 'next-view-transitions';
import { Suspense } from 'react';
import "./globals.scss";

export const metadata: Metadata = {
  title: "Codewithg.com | Guillaume Duhan aka Codewithguillaume",
  description: "Generated by create next app. Haha.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <ViewTransitions>
        <body className="container mx-auto grid gap-4 py-4">
          <DarkMode />
          <Suspense>
            {children}
          </Suspense>
        </body>
      </ViewTransitions>
    </html>
  );
}
