<script setup>
const ideasList = [
    {
        "year": "2022",
        "title": "freebusinessideas.com",
        "description": "Find good business ideas",
        "dead": true
    },
    {
        "year": "2022",
        "title": "findinternship.com",
        "description": "Post internships offers",
        "dead": true
    },
    {
        "year": "2022",
        "title": "findwork.com",
        "description": "Post jobs offers",
        "dead": true
    },
    {
        "year": "2022",
        "title": "besttutorials.com",
        "description": "Best tutorials on everything",
        "dead": true
    },
    {
        "year": "2022",
        "title": "airbnb-photographer.com",
        "description": "Find a photographer for my Airbnb",
        "dead": true
    },
    {
        "year": "2022",
        "title": "bestworkshops.com",
        "description": "Organize your workshop now online",
        "dead": true
    },
    {
        "year": "2022",
        "title": "blockchainjobs.gg",
        "description": "Post & browse blockchains jobs",
        "dead": false
    },
    {
        "year": "2022",
        "title": "vueworkshop.gg",
        "description": "workshop remote 3 days to learn vue",
        "dead": false
    },
    {
        "year": "2022",
        "title": "Brandmy.team",
        "description": "Brandmy.team - create merch for your brand on 1 click",
        "dead": true
    },
    {
        "year": "2022",
        "title": "creatorfund.com",
        "description": "Fundings for creators",
        "dead": true
    },
    {
        "year": "2022",
        "title": "bestcofounder.com",
        "description": "Find your best cofounder",
        "dead": true
    },
    {
        "year": "2022",
        "title": "vuetifytools.com",
        "description": "resources for vuetify",
        "dead": true
    },
    {
        "year": "2022",
        "title": "vscode-vue.com",
        "description": "Vscode extension to generate vue file",
        "dead": true
    },
    {
        "year": "2022",
        "title": "startuplist.com",
        "description": "list of every start-up in the world",
        "dead": true
    },
    {
        "year": "2022",
        "title": "bestelectriccars.gg",
        "description": "electric cars comparator",
        "dead": false
    },
    {
        "year": "2022",
        "title": "creatorcamp.tv",
        "description": "a camp to help creators to improve their audience",
        "dead": true
    },
    {
        "year": "2022",
        "title": "welcomebaby.app",
        "description": "a crowdfunding app for newborns and babies",
        "dead": true
    },
    {
        "year": "2022",
        "title": "brandambassadors.com",
        "description": "platform to find ambassadors for your brand",
        "dead": true
    },
    {
        "year": "2022",
        "title": "learning-platforms.com",
        "description": "E-learning template for platforms",
        "dead": true
    },
    {
        "year": "2022",
        "title": "testi.fy",
        "description": "Pay to get users reviewing your app… chose how much to reward",
        "dead": true
    },
    {
        "year": "2022",
        "title": "rulify.com",
        "description": "List all your company rules",
        "dead": true
    },
    {
        "year": "2022",
        "title": "Moncarnetdesante.fr",
        "description": "Carnet de santé en ligne",
        "dead": true
    },
    {
        "year": "2022",
        "title": "Apprendre-supabase.fr",
        "description": "Cours complet sur Supabase en Français.",
        "dead": false
    },
    {
        "year": "2022",
        "title": "mastercontent.com",
        "description": "Bot that create daily content for your blog and improve your SEO (content generated by Artificial Intelligence + Trends) - $99 to create up to 3 articles per day on your WordPress, Shopify, Prestashop",
        "dead": true
    },
    {
        "year": "2022",
        "title": "bestcodesnippets.com",
        "description": "List of best snippets code.",
        "dead": true
    },
    {
        "year": "2022",
        "title": "schoolfordev.com",
        "description": "A school for devs.",
        "dead": true
    },
    {
        "year": "2022",
        "title": "bestjobs.tech",
        "description": "A website to find jobs in tech",
        "dead": true
    },
    {
        "year": "2022",
        "title": "clientsy.go",
        "description": "A SaaS to store your clients list",
        "dead": true
    },
    {
        "year": "2023",
        "title": "manageemploye.es",
        "description": "SaaS to manage your employees",
        "dead": true
    },
    {
        "year": "2023",
        "title": "thecontentcreator.business",
        "description": "A complete guide to become a content creator",
        "dead": true
    },
    {
        "year": "2023",
        "title": "meetmetrics.com",
        "description": "A website to get all your metrics on Google Meets.",
        "dead": true
    },
    {
        "year": "2023",
        "title": "FakeSocialCounter",
        "description": "FakeSocialCounter — a fake counter for social medias.",
        "dead": true
    },
    {
        "year": "2023",
        "title": "interestingcalls.com",
        "description": "Meet interesting entrepreneurs",
        "dead": true
    },
    {
        "year": "2023",
        "title": "app-status.com",
        "description": "A website to monitor every app statuses.",
        "dead": true
    },
    {
        "year": "2023",
        "title": "seo-ressources.com",
        "description": "Buy excels of data like restaurants…",
        "dead": true
    },
    {
        "year": "2023",
        "title": "podcastlist.com",
        "description": "List of every podcast with their rates.",
        "dead": true
    },
    {
        "year": "2023",
        "title": "birthlist.com",
        "description": "A list of every birth",
        "dead": true
    },
    {
        "year": "2023",
        "title": "getreviews.com",
        "description": "Reviews platform for every business",
        "dead": false
    },
    {
        "year": "2023",
        "title": "landingmasters.com",
        "description": "A website to generate landing pages",
        "dead": true
    },
    {
        "year": "2023",
        "title": "migrainedata.app",
        "description": "Collect data on migraine for doctors.",
        "dead": false
    },
    {
        "year": "2023",
        "title": "saucer.link",
        "description": "Link reducer, Basic, unlimited links, 5 links per day",
        "dead": true
    },
    {
        "year": "2023",
        "title": "proposal.work",
        "description": "Edit a quote online immediately.",
        "dead": true
    },
    {
        "year": "2023",
        "title": "allnewsletters.com",
        "description": "A list of every newsletter online.",
        "dead": true
    },
    {
        "year": "2023",
        "title": "timeline.baby",
        "description": "A app to save your baby life's timeline",
        "dead": true
    },
    {
        "year": "2023",
        "title": "documentation.ai",
        "description": "AI documentation generator",
        "dead": true
    },
    {
        "year": "2023",
        "title": "findproducer.pro",
        "description": "A marketplace to find your next video producer",
        "dead": true
    },
    {
        "year": "2023",
        "title": "unknown.com",
        "description": "A real estate SaaS",
        "dead": true
    },
    {
        "year": "2023",
        "title": "mécénat.art",
        "description": "Buy and collect art piece from anyone",
        "dead": true
    },
    {
        "year": "2023",
        "title": "firstweek.co",
        "description": "Integrate your new collaborators faster — an app to explain everything about the company and how to integrate them faster",
        "dead": true
    },
    {
        "year": "2023",
        "title": "planelog.co",
        "description": "Track all your travels by plane",
        "dead": true
    },
    {
        "year": "2023",
        "title": "Calendly concurrent",
        "description": "For coaches and people who want to sell their time",
        "dead": true
    },
    {
        "year": "2023",
        "title": "Tech PR agency",
        "description": "a press relations agency for tech",
        "dead": true
    },
    {
        "year": "2023",
        "title": "jobstarter-template.com",
        "description": "A template to start a job board company with Next.js, Resend, Supabase",
        "dead": true
    },
    {
        "year": "2023",
        "title": "whoisthedirector.com",
        "description": "If you find the director, you win",
        "dead": true
    },
    {
        "year": "2023",
        "title": "youtubeTrendsTester.com",
        "description": "A tool for youtuberYoutube planner tester, you create thumbnails & title and you see who click on it.",
        "dead": true
    },
    {
        "year": "2023",
        "title": "templating.co",
        "description": "A marketplace for digital templates",
        "dead": true
    },
    {
        "year": "2023",
        "title": "recruiting-software.com",
        "description": "A software of recruitment",
        "dead": true
    },
    {
        "year": "2023",
        "title": "chrome-amazon-products.com",
        "description": "A chrome extension to detect every product and link them to Amazon",
        "dead": true
    },
    {
        "year": "2024",
        "title": "destinations-ideas.com",
        "description": "A website to know where to go",
        "dead": true
    },
    {
        "year": "2024",
        "title": "rental-credibility.com",
        "description": "Get the best profile to never get rejected",
        "dead": false
    },
    {
        "year": "2024",
        "title": "featured.co",
        "description": "A website to submit new feature to any product on market.",
        "dead": true
    }
]

</script>

<template>
  <div class="grid gap-6">
    <header class="text-center">
      <h1 class="headline">My cemetery of ideas 💀</h1>
      <p>Green = I made it. Red = I failed. Feel free to pick.</p>
    </header>
    <div class="grid gap-4">
      <Card v-for="idea, index in ideasList.reverse()" :key="index" :class="idea.dead ? 'dead' : 'alive'">
        <div class="flex gap-1 text-base">
          <span class="text-white">{{ idea.year }} –</span>
          <span class="text-white">{{ idea.title }} –</span>
          <p class="text-base">{{ idea.description }}</p>
        </div>
      </Card>
    </div>
  </div>
</template>