// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 11/18/2024, 9:17:59 AM
const configMerger = require("/Users/guillaume/Desktop/GUILLAUME/DEV/CODEWITHG.COM/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/guillaume/Desktop/GUILLAUME/DEV/CODEWITHG.COM/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/guillaume/Desktop/GUILLAUME/DEV/CODEWITHG.COM/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/guillaume/Desktop/GUILLAUME/DEV/CODEWITHG.COM/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/guillaume/Desktop/GUILLAUME/DEV/CODEWITHG.COM/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/guillaume/Desktop/GUILLAUME/DEV/CODEWITHG.COM/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/guillaume/Desktop/GUILLAUME/DEV/CODEWITHG.COM/plugins/**/*.{js,ts,mjs}","/Users/guillaume/Desktop/GUILLAUME/DEV/CODEWITHG.COM/composables/**/*.{js,ts,mjs}","/Users/guillaume/Desktop/GUILLAUME/DEV/CODEWITHG.COM/utils/**/*.{js,ts,mjs}","/Users/guillaume/Desktop/GUILLAUME/DEV/CODEWITHG.COM/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/guillaume/Desktop/GUILLAUME/DEV/CODEWITHG.COM/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/guillaume/Desktop/GUILLAUME/DEV/CODEWITHG.COM/app.config.{js,ts,mjs}"] }));

module.exports = config
